rules = [ OrganizeImports, ExplicitResultTypes ]

OrganizeImports {
  importsOrder = Ascii
  importSelectorsOrder = Ascii
  removeUnused = true
  groupedImports = Merge
}

ExplicitResultTypes {
  memberVisibility = [ Public, Protected ]
  skipSimpleDefinitions = true
}
