rules = [ OrganizeImports, ExplicitResultTypes ]

OrganizeImports {
  importsOrder = Ascii
  importSelectorsOrder = Ascii
  removeUnused = true
  groupedImports = Merge
  groups = [
    "lomination.games."
    "org.jline."
    "java."
    "scala."
  ]
  fallbackNamespaces = ["*"]
}

ExplicitResultTypes {
  memberVisibility = [ Public, Protected ]
  skipSimpleDefinitions = true
}
