name: Build and test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Scala and SBT
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.21
          apps: sbt

      - name: Run tests
        run: sbt test

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(sbt -batch -error "print version" | tr -d '\n\r')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Jar
        run: sbt assembly

      - name: Debug Path String
        run: |
          echo "Expected filename: [games-${{ env.VERSION }}.jar]"
          ls -R ${{ github.workspace }}/target/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: games-assembly-${{ env.VERSION }}
          path: ${{ github.workspace }}/target/scala-3.8.3/games-${{ env.VERSION }}.jar
          if-no-files-found: error
