name: Build and test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Scala and SBT
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.21
          apps: sbt

      - name: Run tests
        run: sbt test

      - name: Get project version
        id: get_version
        run: |
          RAW_VERSION=$(sbt -batch -error -no-colors "print version")
          
          # CLEAN_VERSION=$(echo "$RAW_VERSION" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | tr -d '\n\r ')
          
          echo "VERSION=$RAW_VERSION" >> $GITHUB_ENV

      - name: Create Jar
        run: sbt assembly

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: games-assembly-${{ env.VERSION }}
          path: ${{ github.workspace }}/target/scala-3.8.3/games-${{ env.VERSION }}.jar
          if-no-files-found: error
